use serde::{Deserialize, Serialize};
use std::path::Path;

// ── WorkspaceConfig ───────────────────────────────────────────────────────────

/// Workspace-level config stored in `<ai_root>/orbit.toml`.
/// Owned and distributed by the company through the governance repo.
/// Users never edit this directly.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct WorkspaceConfig {
    pub governance: GovernanceSection,
    pub update: UpdateSection,
    pub dev: DevSection,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct DevSection {
    /// SHA-256 hash of the development token.
    /// Format: `sha256:<64-char hex>`.
    /// Generated by `orbit dev generate-token`; admin commits only the hash.
    pub token_hash: String,
}

impl DevSection {
    pub fn is_configured(&self) -> bool {
        !self.token_hash.is_empty()
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct GovernanceSection {
    /// Git URL of the governance repository.
    pub url: String,
    /// Pull governance configs automatically on launch.
    pub auto_sync: bool,
    /// Minimum hours between auto-syncs (0 = every launch).
    pub sync_interval_hours: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct UpdateSection {
    /// Internal URL to download new orbit binaries.
    /// Format: `http://server/orbit/latest/{platform}` where platform is
    /// `linux-x86_64`, `linux-aarch64`, `darwin-x86_64`, `darwin-aarch64`.
    pub binary_url: String,
    /// Check for a newer orbit release on startup (default: true).
    /// Set to false to opt out team-wide. Use ORBIT_NO_UPDATE_CHECK=1 for per-user opt-out.
    pub check_on_startup: bool,
}

impl Default for UpdateSection {
    fn default() -> Self {
        Self {
            binary_url: String::new(),
            check_on_startup: true,
        }
    }
}

// ── load ──────────────────────────────────────────────────────────────────────

impl WorkspaceConfig {
    pub fn load(ai_root: &Path) -> Self {
        let path = ai_root.join("orbit.toml");
        std::fs::read_to_string(&path)
            .ok()
            .and_then(|text| toml::from_str(&text).ok())
            .unwrap_or_default()
    }

    /// `true` when a governance URL has been configured.
    pub fn has_governance(&self) -> bool {
        !self.governance.url.is_empty()
    }

    /// `true` when a binary update URL has been configured.
    pub fn has_binary_url(&self) -> bool {
        !self.update.binary_url.is_empty()
    }

    /// Resolve the binary download URL for the current platform.
    ///
    /// Falls back to the public GitHub releases URL when no custom URL is
    /// configured in orbit.toml.
    pub fn binary_url_for_platform(&self) -> Option<String> {
        let platform = current_platform();
        if !self.update.binary_url.is_empty() {
            let base = self.update.binary_url.trim_end_matches('/');
            Some(format!("{base}/{platform}"))
        } else {
            Some(format!(
                "https://github.com/tensiply/orbit/releases/latest/download/orbit-{platform}"
            ))
        }
    }
}

/// Scan `home` for direct subdirectories that look like orbit workspaces.
/// A workspace directory must contain `orbit.toml` or a `tenants/` subdirectory.
pub fn detect_workspaces(home: &std::path::Path) -> Vec<std::path::PathBuf> {
    let Ok(entries) = std::fs::read_dir(home) else {
        return vec![];
    };
    let mut workspaces: Vec<std::path::PathBuf> = entries
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_dir())
        .filter(|e| {
            let p = e.path();
            p.join("orbit.toml").exists() || p.join("tenants").is_dir()
        })
        .map(|e| e.path())
        .collect();
    workspaces.sort();
    workspaces
}

fn current_platform() -> &'static str {
    match (std::env::consts::OS, std::env::consts::ARCH) {
        ("linux", "x86_64") => "linux-x86_64",
        ("linux", "aarch64") => "linux-aarch64",
        ("macos", "x86_64") => "macos-x86_64",
        ("macos", "aarch64") => "macos-aarch64",
        _ => "linux-x86_64",
    }
}
