use anyhow::Result;
use clap::Args;

#[derive(Debug, Args)]
pub struct ShellInitArgs {
    /// Shell to generate integration for: zsh, bash, fish
    /// Defaults to auto-detect from $SHELL
    pub shell: Option<String>,
}

pub fn run(args: ShellInitArgs) -> Result<()> {
    let shell = match args.shell.as_deref() {
        Some(s) => s.to_string(),
        None => detect_shell(),
    };

    match shell.as_str() {
        "fish" => print!("{}", FISH),
        _ => print!("{}", ZSH_BASH), // works for both zsh and bash
    }

    Ok(())
}

fn detect_shell() -> String {
    std::env::var("SHELL")
        .unwrap_or_default()
        .rsplit('/')
        .next()
        .unwrap_or("zsh")
        .to_string()
}

// ── shell functions ───────────────────────────────────────────────────────────

const ZSH_BASH: &str = r#"# Orbit shell integration — generated by `orbit shell-init`
# Add to ~/.zshrc or ~/.bashrc:
#   eval "$(orbit shell-init)"
orbit() {
    if [[ "${1:-}" == "launch" ]]; then
        local _orbit_dir
        _orbit_dir=$(command orbit launch --print-work-dir "${@:2}" 2>/dev/null)
        [[ -n "$_orbit_dir" && -d "$_orbit_dir" ]] && cd -- "$_orbit_dir"
    fi
    command orbit "$@"
}
"#;

const FISH: &str = r#"# Orbit shell integration — generated by `orbit shell-init fish`
# Add to ~/.config/fish/config.fish:
#   orbit shell-init fish | source
function orbit
    if test (count $argv) -gt 0 -a "$argv[1]" = "launch"
        set -l _orbit_dir (command orbit launch --print-work-dir $argv[2..] 2>/dev/null)
        if test -n "$_orbit_dir" -a -d "$_orbit_dir"
            cd -- $_orbit_dir
        end
    end
    command orbit $argv
end
"#;
